---
- name: Include secret vars
  include_vars:
    file: secrets.yml

- name: "SERI Base"
  ansible.builtin.include_tasks: seri.yml

- name: "HR Resource"
  ansible.builtin.include_tasks: hr.yml
    
- name: "LDAP Resource"
  ansible.builtin.include_tasks: ldap.yml

- name: "EPIC Resource"
  ansible.builtin.include_tasks: epic.yml

- name: "Oracle EBS Resource"
  ansible.builtin.include_tasks: oracleebs.yml

- name: "PRISM Resource"
  ansible.builtin.include_tasks: prism.yml

- name: "TRAKK Resource"
  ansible.builtin.include_tasks: trakk.yml

- name: "TRAKK-WS Resource"
  ansible.builtin.include_tasks: trakk-ws.yml
  
- name: "ERP Portal Resource"
  ansible.builtin.include_tasks: erpportal.yml

- name: "RACF Resource"
  ansible.builtin.include_tasks: racf.yml

- name: Run setup task
  ansible.builtin.shell: 
    cmd: "{{ java_cmd }} console iiqBeans -c \"run 'Setup Task'\""
    stdin: |
      {{ iiq_admin_user }}
      {{ iiq_admin_password }}
  async: 1200
  poll: 5
  register: cmdout
  changed_when: cmdout.rc != 0