---
language: python
services: docker
cache:
  pip: true

env:
  - SCENARIO="backwards_compatibility"
  - SCENARIO="default"
  - SCENARIO="other_features"
  - SCENARIO="tls"

script:
  - molecule test -s ${SCENARIO}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
