---
# - name: "Build war file"
#   ansible.builtin.include_tasks: build_war.yml

- name: "Install IIQ"
  ansible.builtin.include_tasks: install.yml
  when: identityiq_import_custom is false

- name: "Install IIQ With Custom artefacts import"
  ansible.builtin.include_tasks: importcustom.yml
  when: identityiq_import_custom is true
