---
galaxy_info:
  author: Robert de Bock
  namespace: robertdebock
  role_name: java
  description: Install and configure java on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Amazon
      versions:
        - Candidate
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Fedora
      versions:
        - 33
        - 34
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - java
    - oracle
    - openjdk
    - jre
    - jdk
    - alternatives

dependencies: []
