identityiq_tomcat_root: /opt/tomcat

identityiq_home_location: /home/sailpoint
identityiq_hostname: seri

# When using GA version, comment the patch_version and ets_version
identityiq_version: 8.4
identityiq_patch_version: p1
identityiq_import_custom: false
# identityiq_ets_version:

identityiq_admin_user: spadmin

identityiq_root: "{{ identityiq_tomcat_root }}/webapps/identityiq"

identityiq_web_inf_dir: "{{ identityiq_tomcat_root }}/webapps/identityiq/WEB-INF"
identityiq_java_cmd: java -classpath {{ identityiq_web_inf_dir }}/lib/identityiq.jar:{{ identityiq_web_inf_dir }}/classes sailpoint.launch.Launcher

identityiq_logfile_location: /opt/tomcat/logs/sailpoint.log

identityiq_repo_name: "rapidLight"
identityiq_exports_repo_name: "seri-exports"
identityiq_repo_url: "github.com/wim-vandijck-sp/{{ identityiq_repo_name }}"
identityiq_exports_repo_url: "github.com/wim-vandijck-sp/{{ identityiq_exports_repo_name }}"

# git_dest: "{{ identityiq_home_location }}/{{ identityiq_repo_name }}"
identityiq_git_dest: "{{ identityiq_root }}/WEB-INF/config/{{ identityiq_repo_name }}"
