use orangehrm;
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1a2a3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1a2a3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1a2a3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1a2a3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1a2a3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1a2a3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1a2a3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1a2a3d4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1a2b3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1a2b3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1a2b3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1a2b3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1a2b3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1a2b3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1a2b3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1a2b3d4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1a2c3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1a2c3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1a2c3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1a2c3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1a2c3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1a2c3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1a2c3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1a2c3d4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1b2a3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1b2a3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1b2a3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1b2a3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1b2a3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1b2a3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1b2a3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1b2a3d4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1b2b3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1b2b3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1b2b3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1b2b3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1b2b3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1b2b3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1b2b3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1b2b3d4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1b2c3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1b2c3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1b2c3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1b2c3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1b2c3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1b2c3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1b2c3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1b2c3d4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1c2a3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1c2a3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1c2a3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Information Technology' set hs_hr_employee.work_station=dept.id where employee_id='1c2a3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1c2a3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1c2a3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1c2a3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Engineering' set hs_hr_employee.work_station=dept.id where employee_id='1c2a3d4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1c2b3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1c2b3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1c2b3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Human Resources' set hs_hr_employee.work_station=dept.id where employee_id='1c2b3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1c2b3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1c2b3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1c2b3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Inventory' set hs_hr_employee.work_station=dept.id where employee_id='1c2b3d4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1c2c3a4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1c2c3a4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1c2c3b4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Accounting' set hs_hr_employee.work_station=dept.id where employee_id='1c2c3b4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1c2c3c4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1c2c3c4d';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1c2c3d4c';
update hs_hr_employee inner join ohrm_subunit as dept on dept.name='Finance' set hs_hr_employee.work_station=dept.id where employee_id='1c2c3d4d';
