update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Global Infrastructure Manager' set emp.job_title_code=job.id where emp.employee_id='1a2a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Global Infrastructure Manager' set emp.job_title_code=job.id where emp.employee_id='1a2aX';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='IT Database Manager' set emp.job_title_code=job.id where emp.employee_id='1a2a3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Information Security Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2a3b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Senior Production Manager' set emp.job_title_code=job.id where emp.employee_id='1a2a3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Production Manager' set emp.job_title_code=job.id where emp.employee_id='1a2a3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='HR Manager' set emp.job_title_code=job.id where emp.employee_id='1a2b3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Training & Development Specialist' set emp.job_title_code=job.id where emp.employee_id='1a2b3b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Manager' set emp.job_title_code=job.id where emp.employee_id='1a2b3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Cost Savings Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2b3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Senior Finance Manager' set emp.job_title_code=job.id where emp.employee_id='1a2c3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Data Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Planning Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='RACF Security Administrator' set emp.job_title_code=job.id where emp.employee_id='1a2a3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Oracle Administrator' set emp.job_title_code=job.id where emp.employee_id='1a2a3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='SQL Server Administrator' set emp.job_title_code=job.id where emp.employee_id='1a2a3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Information Security Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2a3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Information Security Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2a3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Production Developer I' set emp.job_title_code=job.id where emp.employee_id='1a2a3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Production Developer II' set emp.job_title_code=job.id where emp.employee_id='1a2a3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Production Developer I' set emp.job_title_code=job.id where emp.employee_id='1a2a3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Staging Test Engineer I' set emp.job_title_code=job.id where emp.employee_id='1a2a3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Production Test Engineer II' set emp.job_title_code=job.id where emp.employee_id='1a2a3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Production Test Engineer I' set emp.job_title_code=job.id where emp.employee_id='1a2a3d4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Recruiter' set emp.job_title_code=job.id where emp.employee_id='1a2b3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Recruiter' set emp.job_title_code=job.id where emp.employee_id='1a2b3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Recruiter' set emp.job_title_code=job.id where emp.employee_id='1a2b3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Training & Development Specialist' set emp.job_title_code=job.id where emp.employee_id='1a2b3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Training & Development Specialist' set emp.job_title_code=job.id where emp.employee_id='1a2b3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2b3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst II' set emp.job_title_code=job.id where emp.employee_id='1a2b3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2b3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Cost Savings Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2b3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Cost Savings Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2b3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Cost Savings Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2b3d4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='AP Accounting Manager' set emp.job_title_code=job.id where emp.employee_id='1a2c3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Accounts Payable Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Accounts Payable Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='AR Accounting Manager' set emp.job_title_code=job.id where emp.employee_id='1a2c3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Accounts Receivable Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3b4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Accounts Receivable Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Planning Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Planning Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Planning Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Data Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Data Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Data Analyst' set emp.job_title_code=job.id where emp.employee_id='1a2c3d4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst I' set emp.job_title_code=job.id where emp.employee_id='1b2a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Security Architect' set emp.job_title_code=job.id where emp.employee_id='1b2a3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Telecommunications and Network Manager' set emp.job_title_code=job.id where emp.employee_id='1b2a3b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Staging Manager' set emp.job_title_code=job.id where emp.employee_id='1b2a3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Staging Manager' set emp.job_title_code=job.id where emp.employee_id='1b2a3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Compensation' set emp.job_title_code=job.id where emp.employee_id='1b2b3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Employment Manager' set emp.job_title_code=job.id where emp.employee_id='1b2b3b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Manager' set emp.job_title_code=job.id where emp.employee_id='1b2b3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Buyer' set emp.job_title_code=job.id where emp.employee_id='1b2b3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Payroll Manager' set emp.job_title_code=job.id where emp.employee_id='1b2c3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Payroll Manager' set emp.job_title_code=job.id where emp.employee_id='1b2c3b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Treasury Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2c3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Treasury Researcher' set emp.job_title_code=job.id where emp.employee_id='1b2c3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Security Architect' set emp.job_title_code=job.id where emp.employee_id='1b2a3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Security Architect' set emp.job_title_code=job.id where emp.employee_id='1b2a3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Security Architect' set emp.job_title_code=job.id where emp.employee_id='1b2a3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Network Systems Administrator' set emp.job_title_code=job.id where emp.employee_id='1b2a3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Network Systems Administrator' set emp.job_title_code=job.id where emp.employee_id='1b2a3b4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Data Communications Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2a3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Staging Developer II' set emp.job_title_code=job.id where emp.employee_id='1b2a3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst I' set emp.job_title_code=job.id where emp.employee_id='1b2a3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst I' set emp.job_title_code=job.id where emp.employee_id='1b2a3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Staging Test Engineer I' set emp.job_title_code=job.id where emp.employee_id='1b2a3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Production Test Engineer I' set emp.job_title_code=job.id where emp.employee_id='1b2a3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Staging Developer I' set emp.job_title_code=job.id where emp.employee_id='1b2a3d4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Compensation' set emp.job_title_code=job.id where emp.employee_id='1b2b3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Compensation' set emp.job_title_code=job.id where emp.employee_id='1b2b3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Compensation' set emp.job_title_code=job.id where emp.employee_id='1b2b3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Employee Relations Manager' set emp.job_title_code=job.id where emp.employee_id='1b2b3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Employee Relations Manager' set emp.job_title_code=job.id where emp.employee_id='1b2b3b4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Employee Relations Manager' set emp.job_title_code=job.id where emp.employee_id='1b2b3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Buyer' set emp.job_title_code=job.id where emp.employee_id='1b2b3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Buyer' set emp.job_title_code=job.id where emp.employee_id='1b2b3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst II' set emp.job_title_code=job.id where emp.employee_id='1b2b3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Buyer' set emp.job_title_code=job.id where emp.employee_id='1b2b3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Buyer' set emp.job_title_code=job.id where emp.employee_id='1b2b3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Procurement Buyer' set emp.job_title_code=job.id where emp.employee_id='1b2b3d4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Payroll Analyst I' set emp.job_title_code=job.id where emp.employee_id='1b2c3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Payroll Analyst I' set emp.job_title_code=job.id where emp.employee_id='1b2c3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Payroll Analyst II' set emp.job_title_code=job.id where emp.employee_id='1b2c3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Senior Payroll Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2c3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Senior Payroll Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2c3b4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Payroll Analyst I' set emp.job_title_code=job.id where emp.employee_id='1b2c3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Treasury Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2c3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Treasury Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2c3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst II' set emp.job_title_code=job.id where emp.employee_id='1b2c3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Treasury Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2c3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Treasury Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2c3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Treasury Analyst' set emp.job_title_code=job.id where emp.employee_id='1b2c3d4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Operations Manager' set emp.job_title_code=job.id where emp.employee_id='1c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='SOX Access Reviewer' set emp.job_title_code=job.id where emp.employee_id='1c2a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Operations Director' set emp.job_title_code=job.id where emp.employee_id='1c2b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Operations Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='IT Distributed Systems Manager' set emp.job_title_code=job.id where emp.employee_id='1c2a3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Internal Audit Manager' set emp.job_title_code=job.id where emp.employee_id='1c2a3b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Internal Development Manager' set emp.job_title_code=job.id where emp.employee_id='1c2a3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Internal QA Manager' set emp.job_title_code=job.id where emp.employee_id='1c2a3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Compensation & Benefits Manager' set emp.job_title_code=job.id where emp.employee_id='1c2b3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Compensation & Benefits Manager' set emp.job_title_code=job.id where emp.employee_id='1c2b3b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Manager' set emp.job_title_code=job.id where emp.employee_id='1c2b3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Manager' set emp.job_title_code=job.id where emp.employee_id='1c2b3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Tax Accountant' set emp.job_title_code=job.id where emp.employee_id='1c2c3a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Tax Accountant' set emp.job_title_code=job.id where emp.employee_id='1c2c3b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst III' set emp.job_title_code=job.id where emp.employee_id='1c2c3c';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Systems Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c3d';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Windows Administrator' set emp.job_title_code=job.id where emp.employee_id='1c2a3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Helpdesk Associate' set emp.job_title_code=job.id where emp.employee_id='1c2a3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Windows Administrator' set emp.job_title_code=job.id where emp.employee_id='1c2a3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Internal Auditor' set emp.job_title_code=job.id where emp.employee_id='1c2a3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Unix Administrator' set emp.job_title_code=job.id where emp.employee_id='1c2a3b4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Internal Auditor' set emp.job_title_code=job.id where emp.employee_id='1c2a3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Product Developer I' set emp.job_title_code=job.id where emp.employee_id='1c2a3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Product Developer II' set emp.job_title_code=job.id where emp.employee_id='1c2a3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Product Developer III' set emp.job_title_code=job.id where emp.employee_id='1c2a3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='QA Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2a3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='QA Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2a3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='QA Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2a3d4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Benefits Manager' set emp.job_title_code=job.id where emp.employee_id='1c2b3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Benefits Clerk' set emp.job_title_code=job.id where emp.employee_id='1c2b3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Benefits Clerk' set emp.job_title_code=job.id where emp.employee_id='1c2b3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Benefits Manager' set emp.job_title_code=job.id where emp.employee_id='1c2b3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Benefits Clerk' set emp.job_title_code=job.id where emp.employee_id='1c2b3b4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Benefits Clerk' set emp.job_title_code=job.id where emp.employee_id='1c2b3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst I' set emp.job_title_code=job.id where emp.employee_id='1c2b3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst I' set emp.job_title_code=job.id where emp.employee_id='1c2b3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Inventory Analyst I' set emp.job_title_code=job.id where emp.employee_id='1c2b3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Receiving Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2b3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Receiving Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2b3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Receiving Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2b3d4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Tax Accountant' set emp.job_title_code=job.id where emp.employee_id='1c2c3a4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Tax Accountant' set emp.job_title_code=job.id where emp.employee_id='1c2c3a4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Tax Accountant' set emp.job_title_code=job.id where emp.employee_id='1c2c3a4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Accounts Payable Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c3b4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Tax Accountant' set emp.job_title_code=job.id where emp.employee_id='1c2c3b4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Tax Accountant' set emp.job_title_code=job.id where emp.employee_id='1c2c3b4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Systems Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c3c4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Systems Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c3c4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Systems Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c3c4e';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Systems Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c3d4a';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Systems Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c3d4b';
update orangehrm.hs_hr_employee as emp inner join orangehrm.ohrm_job_title as job on job.job_title='Financial Systems Analyst' set emp.job_title_code=job.id where emp.employee_id='1c2c3d4e';
