insert into orangehrm.ohrm_job_title(job_title) values ('Accounts Payable Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Accounts Receivable Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('AP Accounting Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('AR Accounting Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Benefits Clerk');
insert into orangehrm.ohrm_job_title(job_title) values ('Benefits Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Compensation');
insert into orangehrm.ohrm_job_title(job_title) values ('Compensation & Benefits Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Cost Savings Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Data Communications Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Employee Relations Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Employment Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Financial Planning Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Financial Systems Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Global Infrastructure Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Helpdesk Associate');
insert into orangehrm.ohrm_job_title(job_title) values ('HR Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Information Security Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Internal Audit Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Internal Auditor');
insert into orangehrm.ohrm_job_title(job_title) values ('Internal Development Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Internal QA Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Inventory Analyst I');
insert into orangehrm.ohrm_job_title(job_title) values ('Inventory Analyst II');
insert into orangehrm.ohrm_job_title(job_title) values ('Inventory Analyst III');
insert into orangehrm.ohrm_job_title(job_title) values ('Inventory Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('IT Database Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('IT Distributed Systems Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Network Systems Administrator');
insert into orangehrm.ohrm_job_title(job_title) values ('Operations Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Operations Director');
insert into orangehrm.ohrm_job_title(job_title) values ('Operations Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Oracle Administrator');
insert into orangehrm.ohrm_job_title(job_title) values ('Payroll Analyst I');
insert into orangehrm.ohrm_job_title(job_title) values ('Payroll Analyst II');
insert into orangehrm.ohrm_job_title(job_title) values ('Payroll Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Procurement Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Procurement Buyer');
insert into orangehrm.ohrm_job_title(job_title) values ('Procurement Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Product Developer I');
insert into orangehrm.ohrm_job_title(job_title) values ('Product Developer II');
insert into orangehrm.ohrm_job_title(job_title) values ('Product Developer III');
insert into orangehrm.ohrm_job_title(job_title) values ('Production Developer I');
insert into orangehrm.ohrm_job_title(job_title) values ('Production Developer II');
insert into orangehrm.ohrm_job_title(job_title) values ('Production Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Production Test Engineer I');
insert into orangehrm.ohrm_job_title(job_title) values ('Production Test Engineer II');
insert into orangehrm.ohrm_job_title(job_title) values ('QA Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('RACF Security Administrator');
insert into orangehrm.ohrm_job_title(job_title) values ('Receiving Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Recruiter');
insert into orangehrm.ohrm_job_title(job_title) values ('Security Architect');
insert into orangehrm.ohrm_job_title(job_title) values ('Senior Finance Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Senior Payroll Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Senior Production Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('SOX Access Reviewer');
insert into orangehrm.ohrm_job_title(job_title) values ('SQL Server Administrator');
insert into orangehrm.ohrm_job_title(job_title) values ('Staging Developer I');
insert into orangehrm.ohrm_job_title(job_title) values ('Staging Developer II');
insert into orangehrm.ohrm_job_title(job_title) values ('Staging Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Staging Test Engineer I');
insert into orangehrm.ohrm_job_title(job_title) values ('Tax Accountant');
insert into orangehrm.ohrm_job_title(job_title) values ('Telecommunications and Network Manager');
insert into orangehrm.ohrm_job_title(job_title) values ('Training & Development Specialist');
insert into orangehrm.ohrm_job_title(job_title) values ('Treasury Analyst');
insert into orangehrm.ohrm_job_title(job_title) values ('Treasury Researcher');
insert into orangehrm.ohrm_job_title(job_title) values ('Unix Administrator');
insert into orangehrm.ohrm_job_title(job_title) values ('Windows Administrator');
