---
- name: prepare
  hosts: all
  become: yes
  gather_facts: true

  roles:
    - role: init
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.update
      update_reboot: no
    - role: robertdebock.java
    - role: robertdebock.tomcat
      tomcat_version: 9
      tomcat_version9: 9.0.45
      tomcat_xms: 1024M
      tomcat_xmx: 2048M
    - role: robertdebock.mysql
      mysql_databases:
        - name: identityiq
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: identityiq
          password: identityiq
          priv: "identityiq.*:ALL"
    - role: lvps.389ds_server
      dirsrv_suffix: dc=seri,dc=sailpointdemo,dc=com
      dirsrv_rootdn: cn=admin
      dirsrv_rootdn_password: S@ilp0!nt
      dirsrv_serverid: customized
      dirsrv_install_examples: true
      dirsrv_logging:
        audit:
          enabled: true
          logrotationtimeunit: day
          logmaxdiskspace: 400
          maxlogsize: 200
          maxlogsperdir: 14
          mode: 600
        access:
          enabled: true
          logrotationtimeunit: day
          logmaxdiskspace: 400
          maxlogsize: 200
          maxlogsperdir: 14
          mode: 600
        error:
          enabled: true
          logrotationtimeunit: day
          logmaxdiskspace: 400
          maxlogsize: 200
          maxlogsperdir: 14
          mode: 600
      plugins_enabled:
        MemberOf Plugin: true
    - role: identityiq