---
- name: bootstrap SERI host
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - "vault/main.yml"
    
  roles:
    - role: init
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.hostname
      hostname: seri
      hostname_reboot: no
    - role: robertdebock.update
      update_reboot: no
    - role: robertdebock.java
      java_version: "11"
    - role: robertdebock.tomcat
      tomcat_version: 9
      tomcat_version9: 9.0.68
      tomcat_xms: 1024M
      tomcat_xmx: 2048M
    - role: robertdebock.mysql
      mysql_databases:
        - name: identityiq
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: identityiq
          password: identityiq
          priv: "identityiq.*:ALL"
    - role: 389-ds
    - role: identityiq
      include_group_management: "no"
    - role: robertdebock.php
    - role: orangehrm
      orangehrm_version: "5.1"