---
- name: bootstrap SERI host
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - "vault/main.yml"

  roles:
    # - role: init
    # - role: robertdebock.bootstrap
    # - role: robertdebock.core_dependencies
    # - role: robertdebock.hostname
    #   vars:
    #     hostname: seri.sailpointdemo.com
    #     hostname_reboot: no
    # - role: robertdebock.update
    #   vars:
    #     update_reboot: no
    # - role: robertdebock.java
    # - role: robertdebock.tomcat
    #   vars:
    #     tomcat_version: 9
    #     tomcat_version9: 9.0.83
    #     tomcat_xms: 1024M
    #     tomcat_xmx: 4092M
    # - role: robertdebock.mysql
    #   vars:
    #     mysql_databases:
    #       - name: identityiq
    #         encoding: utf8
    #         collation: utf8_bin
    #     mysql_users:
    #       - name: identityiq
    #         password: identityiq
    #         priv: "identityiq.*:ALL"
    # - role: identityiq
    #   vars:
    #     include_group_management: "no"
    # - role: 389-ds
    #   tags: ldap
    # - role: robertdebock.php
    # - role: orangehrm
    #   orangehrm_version: "5.3"
    - role: seri