tomcat_root: /opt/tomcat
iiq_root: "{{ tomcat_root }}/webapps/identityiq"
web_inf_dir: "{{ iiq_root }}/WEB-INF"
java_cmd: SPHOME={{ iiq_root }} java -classpath {{ web_inf_dir }}/lib/identityiq.jar:{{ web_inf_dir }}/classes sailpoint.launch.Launcher

iiq_admin_user: spadmin
