---
# tasks file for tomcat

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: loop over tomcat_instances
  ansible.builtin.include: instance.yml
  loop: "{{ tomcat_instances }}"
  loop_control:
    label: "{{ instance.name }}"
    loop_var: instance
  when:
    - tomcat_instances is defined
